### ISSUE TITLE
SupportLibrary 26.1.0 AnimatorCompatHelper multidex error

### ISSUE THREAD

**Issue by Felix58** [mikepenz/ItemAnimators#7]
Since i updated my Project to API 26 i got a NoClassDefFoundError in your Library

`FATAL EXCEPTION: main
                                                                              
                                                                                java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/animation/AnimatorCompatHelper;
                                                                                    at com.mikepenz.itemanimators.BaseItemAnimator.resetAnimation(BaseItemAnimator.java:626)
                                                                                    at com.mikepenz.itemanimators.BaseItemAnimator.changeAnimation(BaseItemAnimator.java:462)
                                                                                    at com.mikepenz.itemanimators.BaseItemAnimator.animateChange(BaseItemAnimator.java:393)`

`Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.animation.AnimatorCompatHelper" on path: DexPathList[####]
                                                                                    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)`

**Comment by mikepenz** [comment]
@Felix58 simply exclude the old support libs version included in this lib. otherwise you will have a conflict

**Comment by Felix58** [comment]
Thank you it worked

**Comment by abdelkerim** [comment]
Hi @mikepenz I have the same problem   how to exclude the old support libs?
here  SCreenshots of my app gradle build (module app) and error I got
![screenshot 191](https://user-images.githubusercontent.com/24291870/39215027-17a6a892-4834-11e8-91a2-bbae7c63c216.png)
![screenshot 192](https://user-images.githubusercontent.com/24291870/39215028-1851134a-4834-11e8-90b2-868431ab14bf.png)
